// Package cmd — llmdocsheader.go writes the header and architecture sections.
package cmd

import (
	"fmt"
	"strings"

	"github.com/alimtvnetwork/gitmap-v9/gitmap/constants"
)

// writeLLMHeader writes the document title and intro.
func writeLLMHeader(sb *strings.Builder) {
	fmt.Fprintf(sb, "# LLM.md — GitMap AI Reference Guide (v%s)\n\n", constants.Version)
	sb.WriteString("> Auto-generated by `gitmap llm-docs`. Designed for LLMs to understand GitMap commands and generate CLI invocations from natural language.\n\n")
	sb.WriteString("## What is GitMap?\n\n")
	sb.WriteString("GitMap is a **command-line tool** written in **Go** that scans, catalogs, and manages Git repositories across a developer's machine. ")
	sb.WriteString("Think of it as a \"package manager for your Git repos\" — it knows where all your repos are, their status, groups, aliases, ")
	sb.WriteString("and can perform batch operations across them.\n\n")
	sb.WriteString("**Key value proposition:** Developers with many Git repos (10–500+) use GitMap to scan, organize, navigate, clone, release, and maintain them from a single CLI.\n\n")
}

// writeLLMArchitecture writes the architecture overview section.
func writeLLMArchitecture(sb *strings.Builder) {
	sb.WriteString("## Architecture Overview\n\n")
	sb.WriteString("```\n")
	sb.WriteString("gitmap (Go CLI binary)\n")
	sb.WriteString("├── cmd/           — Command handlers (one file per command)\n")
	sb.WriteString("├── constants/     — All string literals, error messages, flag names\n")
	sb.WriteString("├── model/         — Data types (ScanRecord, BookmarkRecord, etc.)\n")
	sb.WriteString("├── store/         — SQLite database layer\n")
	sb.WriteString("├── release/       — Release/version parsing and tag management\n")
	sb.WriteString("├── cloner/        — Git clone operations\n")
	sb.WriteString("├── dashboard/     — HTML dashboard generation\n")
	sb.WriteString("├── verbose/       — Debug logging\n")
	sb.WriteString("├── completion/    — Shell completion scripts\n")
	sb.WriteString("├── helptext/      — Embedded Markdown help files (go:embed)\n")
	sb.WriteString("└── scripts/       — Install/uninstall scripts (PowerShell, Bash)\n")
	sb.WriteString("```\n\n")
	sb.WriteString("**Database:** SQLite (single file at `~/.gitmap/gitmap.db`), managed via `store/` package.\n\n")
	sb.WriteString("**Platform:** Cross-platform (Windows, Linux, macOS) with amd64 and arm64 support.\n\n")
}
