// Package formatter — desktopscript.go generates a register-desktop.ps1 script.
// NOTE: Still uses direct fmt.Fprintln approach. Will migrate to template
// after clone.ps1.tmpl is verified working.
package formatter

import (
	"fmt"
	"io"
	"strings"

	"github.com/alimtvnetwork/gitmap-v9/gitmap/model"
)

// WriteDesktopScript writes a PowerShell script that registers repos with GitHub Desktop.
func WriteDesktopScript(w io.Writer, records []model.ScanRecord) error {
	writeDesktopHeader(w, len(records))
	writeDesktopBody(w, records)
	writeDesktopFooter(w)

	return nil
}

// writeDesktopHeader writes the script preamble.
func writeDesktopHeader(w io.Writer, count int) {
	fmt.Fprintln(w, `<#
.SYNOPSIS
    Register cloned repositories with GitHub Desktop.
.DESCRIPTION
    Auto-generated by gitmap. Run this script after cloning
    to add all repositories to GitHub Desktop.
    Requires GitHub Desktop CLI (github) to be available in PATH.
#>`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `param(
    [string]$BaseDir = "."
)`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `# Check if GitHub Desktop CLI is available`)
	fmt.Fprintln(w, `$ghDesktop = Get-Command "github" -ErrorAction SilentlyContinue`)
	fmt.Fprintln(w, `if (-not $ghDesktop) {`)
	fmt.Fprintln(w, `    Write-Host ""`)
	fmt.Fprintln(w, `    Write-Host "  XX GitHub Desktop CLI not found." -ForegroundColor Red`)
	fmt.Fprintln(w, `    Write-Host "    Install GitHub Desktop and ensure 'github' is in your PATH." -ForegroundColor Yellow`)
	fmt.Fprintln(w, `    Write-Host ""`)
	fmt.Fprintln(w, `    exit 1`)
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `Write-Host ""`)
	fmt.Fprintln(w, `Write-Host "  +======================================+" -ForegroundColor DarkCyan`)
	fmt.Fprintln(w, `Write-Host "  |     gitmap -- GitHub Desktop         |" -ForegroundColor DarkCyan`)
	fmt.Fprintln(w, `Write-Host "  +======================================+" -ForegroundColor DarkCyan`)
	fmt.Fprintln(w, `Write-Host ""`)
	fmt.Fprintf(w, "Write-Host \"  Registering %d repositories...\" -ForegroundColor Cyan\n", count)
	fmt.Fprintln(w, `Write-Host ""`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `$succeeded = 0`)
	fmt.Fprintln(w, `$failed = 0`)
	fmt.Fprintln(w)
}

// writeDesktopBody writes a registration block for each repo.
func writeDesktopBody(w io.Writer, records []model.ScanRecord) {
	for i, r := range records {
		writeDesktopEntry(w, r, i+1, len(records))
	}
}

// writeDesktopEntry writes one repo registration block.
func writeDesktopEntry(w io.Writer, r model.ScanRecord, idx, total int) {
	relPath := strings.ReplaceAll(r.RelativePath, "/", "\\")
	fmt.Fprintf(w, "Write-Host \"  [%d/%d] \" -ForegroundColor Magenta -NoNewline\n", idx, total)
	fmt.Fprintf(w, "Write-Host \"%s\" -ForegroundColor White\n", r.RepoName)
	fmt.Fprintf(w, "$repoPath = Join-Path $BaseDir \"%s\"\n", relPath)
	fmt.Fprintf(w, "$repoPath = (Resolve-Path $repoPath -ErrorAction SilentlyContinue).Path\n")
	fmt.Fprintln(w, `if ($repoPath -and (Test-Path $repoPath)) {`)
	fmt.Fprintln(w, `    try {`)
	fmt.Fprintln(w, `        github $repoPath 2>&1 | Out-Null`)
	fmt.Fprintln(w, `        Write-Host "  OK Added to GitHub Desktop" -ForegroundColor Green`)
	fmt.Fprintln(w, `        $succeeded++`)
	fmt.Fprintln(w, `    } catch {`)
	fmt.Fprintln(w, `        Write-Host "  XX Failed: $_" -ForegroundColor Red`)
	fmt.Fprintln(w, `        $failed++`)
	fmt.Fprintln(w, `    }`)
	fmt.Fprintln(w, `} else {`)
	fmt.Fprintf(w, "    Write-Host \"  XX Path not found: %s\" -ForegroundColor Red\n", relPath)
	fmt.Fprintln(w, `    $failed++`)
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
}

// writeDesktopFooter writes the summary section.
func writeDesktopFooter(w io.Writer) {
	fmt.Fprintln(w, `Write-Host ""`)
	fmt.Fprintln(w, `Write-Host "  ======================================" -ForegroundColor DarkCyan`)
	fmt.Fprintln(w, `Write-Host "  OK Registered: $succeeded" -ForegroundColor Green`)
	fmt.Fprintln(w, `Write-Host "  XX Failed:     $failed" -ForegroundColor Red`)
	fmt.Fprintln(w, `Write-Host "  ======================================" -ForegroundColor DarkCyan`)
	fmt.Fprintln(w, `Write-Host ""`)
	fmt.Fprintln(w, `Write-Host "  Done!" -ForegroundColor Green`)
	fmt.Fprintln(w, `Write-Host ""`)
}
