// Package release — workflowreleasescript.go bakes the version into copies
// of release-version.ps1 / release-version.sh and writes them into the
// staging directory so they ship as per-release snapshot install assets.
//
// Spec: spec/01-app/105-release-version-script.md
package release

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/alimtvnetwork/gitmap-v9/gitmap/constants"
	"github.com/alimtvnetwork/gitmap-v9/gitmap/scripts"
	"github.com/alimtvnetwork/gitmap-v9/gitmap/verbose"
)

// releaseScriptSnapshot describes one snapshot to generate.
type releaseScriptSnapshot struct {
	embeddedName string // file inside gitmap/scripts/ embed FS
	outputName   string // filename written into the staging dir
	bakeLine     string // single line to inject at the top of the body
}

// buildReleaseVersionSnapshots generates per-version copies of the
// release-version installer scripts and writes them into stagingDir.
// Returns the list of created file paths so the caller can append them
// to the asset list (which makes them participate in checksums + upload).
func buildReleaseVersionSnapshots(version, stagingDir string) []string {
	if len(version) == 0 || len(stagingDir) == 0 {
		return nil
	}

	snapshots := []releaseScriptSnapshot{
		{
			embeddedName: constants.ScriptReleaseVersionPS1,
			outputName:   fmt.Sprintf(constants.ReleaseVersionSnapshotPS1Fmt, version),
			bakeLine:     fmt.Sprintf("$Version = '%s'", version),
		},
		{
			embeddedName: constants.ScriptReleaseVersionSh,
			outputName:   fmt.Sprintf(constants.ReleaseVersionSnapshotShFmt, version),
			bakeLine:     fmt.Sprintf(`VERSION=%q`, version),
		},
	}

	var produced []string
	for _, s := range snapshots {
		out, err := writeReleaseScriptSnapshot(s, stagingDir)
		if err != nil {
			fmt.Fprintf(os.Stderr, constants.ErrReleaseScriptSnapshot, s.outputName, err)
			continue
		}
		fmt.Printf(constants.MsgReleaseScriptSnapshot, filepath.Base(out))
		produced = append(produced, out)
	}

	return produced
}

// writeReleaseScriptSnapshot reads the embedded script, injects the
// version-baking line just after the parameter block, and writes the
// result to the staging directory.
func writeReleaseScriptSnapshot(s releaseScriptSnapshot, stagingDir string) (string, error) {
	raw, err := scripts.ReadFile(s.embeddedName)
	if err != nil {
		return "", fmt.Errorf("read embedded %s: %w", s.embeddedName, err)
	}

	baked := injectVersionBake(string(raw), s.embeddedName, s.bakeLine)

	outPath := filepath.Join(stagingDir, s.outputName)
	if err := os.WriteFile(outPath, []byte(baked), constants.FilePermission); err != nil {
		return "", fmt.Errorf("write snapshot %s: %w", outPath, err)
	}

	if verbose.IsEnabled() {
		verbose.Get().Log("release-script: baked %s -> %s (%d bytes)",
			s.embeddedName, outPath, len(baked))
	}

	return outPath, nil
}

// injectVersionBake inserts the version assignment so that any later
// param/argument parsing finds the value already set. It also short-
// circuits the "required version" guard so the snapshot needs zero args.
//
// PowerShell: insert immediately after the closing `)` of `param(...)`.
// Bash: insert just before the `set -euo pipefail` line.
// On any parse miss we fall back to prepending — still safe because both
// scripts evaluate top-to-bottom and the bake line is idempotent.
func injectVersionBake(body, embeddedName, bakeLine string) string {
	header := "# Snapshot generated by gitmap release pipeline — version is baked.\n"

	if strings.HasSuffix(embeddedName, ".ps1") {
		marker := "$ErrorActionPreference"
		idx := strings.Index(body, marker)
		if idx < 0 {
			return header + bakeLine + "\n" + body
		}
		return body[:idx] + bakeLine + "\n" + header + body[idx:]
	}

	// Bash variant: inject just before `set -euo pipefail`.
	marker := "set -euo pipefail"
	idx := strings.Index(body, marker)
	if idx < 0 {
		return "#!/usr/bin/env bash\n" + header + bakeLine + "\n" + body
	}
	return body[:idx] + header + bakeLine + "\n\n" + body[idx:]
}
